package org.acme.hr_hiring;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Survey implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Comment")
	private java.lang.String comment;
	@org.kie.api.definition.type.Label(value = "Delivered On Time")
	private java.lang.Boolean deliveredOnTime;
	@org.kie.api.definition.type.Label(value = "Missing Equipment")
	private java.lang.String missingEquipment;
	@org.kie.api.definition.type.Label(value = "Satisfied")
	private java.lang.Boolean satisfied;

	public Survey() {
	}

	public java.lang.String getComment() {
		return this.comment;
	}

	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public java.lang.Boolean getDeliveredOnTime() {
		return this.deliveredOnTime;
	}

	public void setDeliveredOnTime(java.lang.Boolean deliveredOnTime) {
		this.deliveredOnTime = deliveredOnTime;
	}

	public java.lang.String getMissingEquipment() {
		return this.missingEquipment;
	}

	public void setMissingEquipment(java.lang.String missingEquipment) {
		this.missingEquipment = missingEquipment;
	}

	public java.lang.Boolean getSatisfied() {
		return this.satisfied;
	}

	public void setSatisfied(java.lang.Boolean satisfied) {
		this.satisfied = satisfied;
	}

	public Survey(java.lang.String comment, java.lang.Boolean deliveredOnTime,
			java.lang.String missingEquipment, java.lang.Boolean satisfied) {
		this.comment = comment;
		this.deliveredOnTime = deliveredOnTime;
		this.missingEquipment = missingEquipment;
		this.satisfied = satisfied;
	}

}