package com.myspace.hr_hiring;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CandidateSkill implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String skillName;
	private java.lang.String levelOfKnowledge;
	private java.lang.Integer yearsOfExperience;

	public CandidateSkill() {
	}

	public java.lang.String getSkillName() {
		return this.skillName;
	}

	public void setSkillName(java.lang.String skillName) {
		this.skillName = skillName;
	}

	public java.lang.String getLevelOfKnowledge() {
		return this.levelOfKnowledge;
	}

	public void setLevelOfKnowledge(java.lang.String levelOfKnowledge) {
		this.levelOfKnowledge = levelOfKnowledge;
	}

	public java.lang.Integer getYearsOfExperience() {
		return this.yearsOfExperience;
	}

	public void setYearsOfExperience(java.lang.Integer yearsOfExperience) {
		this.yearsOfExperience = yearsOfExperience;
	}

	public CandidateSkill(java.lang.String skillName,
			java.lang.String levelOfKnowledge,
			java.lang.Integer yearsOfExperience) {
		this.skillName = skillName;
		this.levelOfKnowledge = levelOfKnowledge;
		this.yearsOfExperience = yearsOfExperience;
	}

}