package com.myspace.hr_hiring;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HiringPetition implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String jobTitle;
	private java.lang.String jobDescription;
	private java.lang.String location;

	private java.util.List<com.myspace.hr_hiring.CandidateSkill> candidateSkills = new java.util.ArrayList<>();

	private java.util.List<java.lang.String> interviewers;

	private java.lang.Integer salaryMin;

	private java.lang.Integer salaryMax;

	private java.util.List<com.myspace.hr_hiring.JobRoleBenefit> benefits;

	private java.lang.Boolean benefitsApproved;

	private java.lang.String jobType;

	private java.lang.String jobCategory;

	public HiringPetition() {
	}

	public java.lang.String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(java.lang.String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public java.lang.String getJobDescription() {
		return this.jobDescription;
	}

	public void setJobDescription(java.lang.String jobDescription) {
		this.jobDescription = jobDescription;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.util.List<com.myspace.hr_hiring.CandidateSkill> getCandidateSkills() {
		return this.candidateSkills;
	}

	public void setCandidateSkills(
			java.util.List<com.myspace.hr_hiring.CandidateSkill> candidateSkills) {
		this.candidateSkills = candidateSkills;
	}

	public void addCandidateSkill(
			com.myspace.hr_hiring.CandidateSkill candidateSkill) {
		this.candidateSkills.add(candidateSkill);
	}

	public java.util.List<java.lang.String> getInterviewers() {
		return this.interviewers;
	}

	public void setInterviewers(java.util.List<java.lang.String> interviewers) {
		this.interviewers = interviewers;
	}

	public java.lang.Integer getSalaryMin() {
		return this.salaryMin;
	}

	public void setSalaryMin(java.lang.Integer salaryMin) {
		this.salaryMin = salaryMin;
	}

	public java.lang.Integer getSalaryMax() {
		return this.salaryMax;
	}

	public void setSalaryMax(java.lang.Integer salaryMax) {
		this.salaryMax = salaryMax;
	}

	public java.util.List<com.myspace.hr_hiring.JobRoleBenefit> getBenefits() {
		return this.benefits;
	}

	public void setBenefits(
			java.util.List<com.myspace.hr_hiring.JobRoleBenefit> benefits) {
		this.benefits = benefits;
	}

	public java.lang.Boolean getBenefitsApproved() {
		return this.benefitsApproved;
	}

	public void setBenefitsApproved(java.lang.Boolean benefitsApproved) {
		this.benefitsApproved = benefitsApproved;
	}

	public java.lang.String getJobType() {
		return this.jobType;
	}

	public void setJobType(java.lang.String jobType) {
		this.jobType = jobType;
	}

	public java.lang.String getJobCategory() {
		return this.jobCategory;
	}

	public void setJobCategory(java.lang.String jobCategory) {
		this.jobCategory = jobCategory;
	}

	public HiringPetition(
			java.lang.String jobTitle,
			java.lang.String jobDescription,
			java.lang.String location,
			java.util.List<com.myspace.hr_hiring.CandidateSkill> candidateSkills,
			java.util.List<java.lang.String> interviewers,
			java.lang.Integer salaryMin, java.lang.Integer salaryMax,
			java.util.List<com.myspace.hr_hiring.JobRoleBenefit> benefits,
			java.lang.Boolean benefitsApproved, java.lang.String jobType,
			java.lang.String jobCategory) {
		this.jobTitle = jobTitle;
		this.jobDescription = jobDescription;
		this.location = location;
		this.candidateSkills = candidateSkills;
		this.interviewers = interviewers;
		this.salaryMin = salaryMin;
		this.salaryMax = salaryMax;
		this.benefits = benefits;
		this.benefitsApproved = benefitsApproved;
		this.jobType = jobType;
		this.jobCategory = jobCategory;
	}

}