package com.myspace.hr_hiring;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InterviewerFeedback implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String interviewer;
	private java.lang.String comment;
	private java.lang.Integer candidateScore;

	public InterviewerFeedback() {
	}

	public java.lang.String getInterviewer() {
		return this.interviewer;
	}

	public void setInterviewer(java.lang.String interviewer) {
		this.interviewer = interviewer;
	}

	public java.lang.String getComment() {
		return this.comment;
	}

	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public java.lang.Integer getCandidateScore() {
		return this.candidateScore;
	}

	public void setCandidateScore(java.lang.Integer candidateScore) {
		this.candidateScore = candidateScore;
	}

	public InterviewerFeedback(java.lang.String interviewer,
			java.lang.String comment, java.lang.Integer candidateScore) {
		this.interviewer = interviewer;
		this.comment = comment;
		this.candidateScore = candidateScore;
	}

}