package com.myspace.hr_hiring;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class JobApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean internal;
	private java.lang.String applicantName;

	private java.util.List<com.myspace.hr_hiring.CandidateSkill> skills;

	public JobApplication() {
	}

	public java.lang.Boolean getInternal() {
		return this.internal;
	}

	public void setInternal(java.lang.Boolean internal) {
		this.internal = internal;
	}

	public java.lang.String getApplicantName() {
		return this.applicantName;
	}

	public void setApplicantName(java.lang.String applicantName) {
		this.applicantName = applicantName;
	}

	public java.util.List<com.myspace.hr_hiring.CandidateSkill> getSkills() {
		return this.skills;
	}

	public void setSkills(
			java.util.List<com.myspace.hr_hiring.CandidateSkill> skills) {
		this.skills = skills;
	}

	public JobApplication(java.lang.Boolean internal,
			java.lang.String applicantName,
			java.util.List<com.myspace.hr_hiring.CandidateSkill> skills) {
		this.internal = internal;
		this.applicantName = applicantName;
		this.skills = skills;
	}

}