package com.myspace.hr_hiring;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class JobRoleBenefit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String benefitName;
	private java.lang.String benefitDescription;

	public JobRoleBenefit() {
	}

	public java.lang.String getBenefitName() {
		return this.benefitName;
	}

	public void setBenefitName(java.lang.String benefitName) {
		this.benefitName = benefitName;
	}

	public java.lang.String getBenefitDescription() {
		return this.benefitDescription;
	}

	public void setBenefitDescription(java.lang.String benefitDescription) {
		this.benefitDescription = benefitDescription;
	}

	public JobRoleBenefit(java.lang.String benefitName,
			java.lang.String benefitDescription) {
		this.benefitName = benefitName;
		this.benefitDescription = benefitDescription;
	}

}